#!/bin/bash
#$ -q long-centos79
#$ -N chen_dw
#$ -t 1-2
#$ -l virtual_free=500M,disk=300G
#$ -cwd
#$ -V

INPUT=$(/bin/sed -n ${SGE_TASK_ID}p ~/4_chen/acc_list.txt)

java -jar ena-file-downloader.jar --accessions=$INPUT --format=READS_FASTQ --location=/nfs/no_backup/flomics/ctuni/4_chen/ --protocol=FTP --asperaLocation=null
